version: '3.0'

services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j-container
    ports:
      - "7474:7474"
      - "7687:7687"
#    environment:
#      NEO4J_AUTH: neo4j/damir12345

#    volumes:
#      - ./neo4j-data:/data
#      - ./neo4j-import:/var/lib/neo4j/import
