version: "3"

services:

  broker-service:
    build:
      context: ./../broker-service
      dockerfile: ../broker-service/broker-service.dockerfile
#    restart: always
    ports:
      - "8000:8000"
    deploy:
      mode: replicated
      replicas: 1

  auth-service:
    build:
      context: ./../auth-service
      dockerfile: ./../auth-service/auth-service.dockerfile
    ports:
      - "8001:8001"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DSN: "host=postgres port=5433 user=postgres password=password dbname=users sslmode=disable timezone=UTC connect_timeout=5"

  postgres:
    image: 'postgres:14.0'
    ports:
      - "5433:5433"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      PG_USER: postgres
      PG_PAS: password
      PG_DB: users
    volumes:
      - ./db_data/postgres/:/lib/postgresql/data/