version: "3"

services:

  broker-service:
    build:
      context: ./../broker-service
      dockerfile: ../broker-service/broker-service.dockerfile
#    restart: always
    ports:
      - "8000:80"
    deploy:
      mode: replicated
      replicas: 1

  auth-service:
    build:
      context: ./../auth-service
      dockerfile: ./../auth-service/auth-service.dockerfile
    ports:
      - "8001:80"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DSN: "host=db port=5432 user=damir password=password dbname=users sslmode=disable timezone=UTC connect_timeout=5"

  db:
    image: 'postgres:14.0'
    ports:
      - "5432:5432"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: damir
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: