version: '3.1'

services:
  oracle-db:
    image: container-registry.oracle.com/database/standard:19.3.0.0
    container_name: oracle-db
    ports:
      - "1521:1521"
    environment:
      - ORACLE_SID=ORCLCDB1
      - ORACLE_PDB=ORCLPDB1
      - ORACLE_PWD=12345
      - ORACLE_CHARACTERSET=AL32UTF8
    volumes:
      - oracle-data:/opt/oracle/oradata

volumes:
  oracle-data:
    driver: local
